name = "resources"
description = "Utility library to handle project resources at run-time"
version = "0.1.0"

licenses = "MIT"
website = "https://github.com/alire-project/resources"
tags = ["utils"]

authors = ["Alire Team"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau", "mosteo"]

[[actions]]
type="test"
command=["alr", "-C", "tests", "build", "--validation"]

[[actions]]
type="test"
command=["alr", "-C", "tests", "run"]
